### ISSUE TITLE
converted world only generates sand

### ISSUE THREAD

**Issue by S21810014** [jgosar/mine-city-2000#1]
the terrain were correctly converted, but the entire map is only consist of sand blocks
![image](https://user-images.githubusercontent.com/74723356/174600595-b8891479-53cf-4b67-8c53-8050179a3dd5.png)

**Comment by jgosar** [comment]
Interesting, maybe the DOS version of SimCity 2000 generates files differently than the Windows one. Can you attach the ˙.sc2` file, so I can check?

Another possible reason for this happening would be if the app wasn't able to access the `.mca`files in the `buildings` directory

**Comment by S21810014** [comment]
here's the savefile, does the 'building' folder has to be in the same directory as the executable? i compiled the entire solution and the executables were stored in 'bin' folder

[.sc2 save file](http://cloud.merfry.space/s/yh0DX6cjZjv6gs0)

**Comment by S21810014** [comment]
yep, it appears that moving the 'buildings' folder to the same dir as the executable works

![image](https://user-images.githubusercontent.com/74723356/174605492-64eeb900-ee26-4c19-b577-90f7a513bd59.png)

**Comment by jgosar** [comment]
@S21810014 I know that you had this problem a really long time ago, but this should be fixed now. I upgraded the projects to .NET 8, and added copying of the buildings dir to the correct place as a build step.
